### ISSUE TITLE
Configure Travis webhook

### ISSUE THREAD

**Issue by octonato** [lagom/akka-grpc-lagom-quickstart-java#3]
Once we start with this repo and add a Travis file, we should add the config below. This will post Travis activity to [gitter:lagom/contributors](https://gitter.im/lagom/contributors?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

```
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never
```
